### PR TITLE
Add autostart input

### PR DESCRIPTION
**Pull request by julienloizelet**
Hi,

by default, ddev starts automatically at the end of the action and, "for some reasons", I didn't want that.
So, I added an `autostart` input that will allow user to decide if he wants ddev to start automatically or not.

For backward compatibility, I set the default value of `autostart` to true.

I had to update dependencies because the method `core.getBooleanInput` is quite recent.

Feel free to close this PR is you think this is useless, but I would like to share.

Thanks

### CODE REVIEW

**Comment by jonaseberle** [comment]
Hi Julien,
I am not opposed to that at all. But I am interested what your use case was.
Thank you!

**Comment by julienloizelet** [comment]
> Hi Julien,
> I am not opposed to that at all. But I am interested what your use case was.
> Thank you!

Well, my use case is not very significant as my workflow was achievable even without my PR ....

Indeed, I am using ddev to launch a Magento 2 environment.

When you run a `ddev start` with ddev magento 2 project type set in the config.yaml,  ddev will create some folders and files (app/etc/env.php, etc., etc.) in the .ddev's parent folder. 

So, running this `github-action-setup-ddev` was actually installing ddev but also launch all this possible post-start hook.

And I found that it could become "messy" (but this is purely subjective). 

I preferred to be able to "just install ddev"  and start it further in the workflow.

**Comment by rfay** [comment]
@julienloizelet you know that you could use `disable_settings_management: true` and ddev won't create any specific settings files or try to manage them, right?

**Comment by julienloizelet** [comment]
> disable_settings_management

Oh! I had missed out on this option. Thanks for the tip.

**Comment by jonaseberle** [comment]
I'll merge that. Thank you! 
I am planning to improve docs and testing in the next days and do a release then.

**Pull request merged**
