### PR TITLE
Delete install_ddev.sh after install

### LINKED ISSUE #20: Remove the install_ddev.sh file after install
It would be nice if this action could clean up the install file it downloads, since it downloads to the current directory, which could be in the workspace of the checked out Github repository.

### PR DESCRIPTION
**Pull request by davereid-pfg**
Fixes #20

### CODE REVIEW

**Review by jonaseberle — APPROVED** [review]

**Comment by rfay** [comment]
Instead of this I recommend switching from install_ddev.sh to installing ddev via the apt repositories, https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#apt-packages-for-debian-based-systems (linux tab)

**Comment by jonaseberle** [comment]
Thanks!

**Comment by rfay** [comment]
Also note that the recommended install_ddev.sh technique has changed where it never downloads, just pipes.

**Comment by davereid-pfg** [comment]
Oh good point, I submitted https://github.com/jonaseberle/github-action-setup-ddev/pull/23 as well.

**Pull request merged**
