### PR TITLE
Adjust nginx.tmpl to current ddev-router, fixes #5

### LINKED ISSUE #5: Starting ddev fails with Error: 1
```
ddev-router is up-to-date

Failed to start project: ddev-router failed to become ready; debug with 'docker logs ddev-router'; logOutput=, err=health check timed out: labels map[com.docker.compose.service:ddev-router] timed out without becoming healthy, status=

Error: 1
```

See #4 for my GitHub workflow.

-----------------------
It seems the previous fix for nginx-router
jwilder/docker-gen#315
https://github.com/jonaseberle/github-action-setup-ddev/blob/master/.ddev/patches/ddev-router/nginx.tmpl
does not do its job any more.

### PR DESCRIPTION
**Pull request by rfay**
The nginx.tmpl pushed into ddev-router was quite old and needed to be updated to match current ddev v1.16.1

This also
* Simplifies the ddev installation and removes use of homebrew
* Stops installing docker and docker-compose as they're already there

I just had to do those because I was waiting too long for everything, sorry to do them in this PR.

What we really need to do though is to debug the original problem, so that will come next. It's also possible now to do something much more elegant than the `docker cp` and we can override the configuration for ddev-router. So at the very least we can do that.

### CODE REVIEW

**Comment by rfay** [comment]
I'm not entirely sure why this can't be boiled down to just

`- run: ddev start || ( docker cp nginx.tmpl ddev-router:/app && ddev start )`

But it seems like it's doing an awful lot there.

**Comment by rfay** [comment]
I'm a n00b to github actions, so don't know how to submit this PR and point the to the right action, so temporarily 
```
- uses: rfay/github-action-setup-ddev@20201122_update_to_ddev_1.16
```

**Comment by rfay** [comment]
Now it works without the `docker cp` or the need to fail once. Mounts the nginx.tmpl into the container using router-compose.nginx_tmpl.yaml.

**Comment by jonaseberle** [comment]
Amazing, @rfay! Thank you very much for your dedication!

**Comment by jonaseberle** [comment]
Your installation also seems to be a lot quicker than the former one with linuxbrew :)

**Comment by jonaseberle** [comment]
> I'm not entirely sure why this can't be boiled down to just
> 
> `- run: ddev start || ( docker cp nginx.tmpl ddev-router:/app && ddev start )`
> 
> But it seems like it's doing an awful lot there.

I have kept that in in the hope that one day we wouldn't need the nginx.tmpl-override. It's good that you removed it.

**Comment by rfay** [comment]
Yeah, homebrew on Linux is just too slow. Gets tiring. I think it's OK for everyday use, but not for start-from-scratch-every-time like this.

Now we just have to figure out how to work around the basic problem. Wish I completely understood it. We probably have to solve it for https://github.com/drud/ddev/pull/2615 so it would be nice to actually understand the issue.

**Comment by rfay** [comment]
@jonaseberle any thoughts on how to make the tests on an action like this actual use the contents of the PR, without doing what I had to do? (Thanks for adjusting it after)

**Comment by jonaseberle** [comment]
@rfay maybe it could work with variables like

    - uses: ${{GITHUB_REPOSITORY}}@${{GITHUB_SHA}}

but I have not tried that yet.

**Comment by jonaseberle** [comment]
I have tagged this as v1.2.0.

**Comment by rfay** [comment]
Oh @jonaseberle I didn't understand why the same stuff was done in https://github.com/jonaseberle/github-action-setup-ddev/blob/master/lib/main.js and also in https://github.com/jonaseberle/github-action-setup-ddev/blob/master/src/main.ts ?

**Comment by jonaseberle** [comment]
The .js is what is actually run. I used TypeScript source although really not necessary for that little code.

It is compiled by
EDIT: Even I didn't remember what I used... - note to self: document dev environment...

    yarn install
    yarn build

Nevermind - I'll get rid of the TypeScript.

**Comment by rfay** [comment]
Ah, I did the `yarn install` but not the `yarn build` when exploring it.

**Comment by jonaseberle** [comment]
Having the node_modules in there feels awkward, but I guess it is still recommended.

**Pull request merged**
