### PR TITLE
Update install to use apt installation

### PR DESCRIPTION
**Pull request by davereid-pfg**

### CODE REVIEW

**Comment by davereid-pfg** [comment]
Any chance we could also get an update to v1 after this too?

**Comment by jonaseberle** [comment]
Could you update to try the `apt` way https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#apt-packages-for-debian-based-systems ?

@rfay I guess we do not need to install the dependencies https://github.com/jonaseberle/github-action-setup-ddev/blob/master/lib/main.js#L62 then either?

**Comment by rfay** [comment]
That's correct, the apt install gets the dependencies.

**Comment by jonaseberle** [comment]
Maybe it needs a `mkcert -install` now.

**Comment by jonaseberle** [comment]
Is this ready to go in?

**Comment by davereid-pfg** [comment]
Good from my end I think.

**Comment by jonaseberle** [comment]
Then let's have it. Thank you!
I am going to tag a new version.

**Pull request merged**
